// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChz-PNhuX9XXqfiZw-m1LkJEiKR8Mb_tE',
    appId: '1:245483000315:android:8bc70442209dcb3bd9bb5e',
    messagingSenderId: '245483000315',
    projectId: 'acro-gate',
    storageBucket: 'acro-gate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1yrdc3wfBlF5d-sUeAFvfS5s87h3uqcY',
    appId: '1:245483000315:ios:415248b79d69c0ddd9bb5e',
    messagingSenderId: '245483000315',
    projectId: 'acro-gate',
    storageBucket: 'acro-gate.appspot.com',
    androidClientId: '245483000315-sqo9sbeva8c9f02ih3jisfo64cpsn4tn.apps.googleusercontent.com',
    iosClientId: '245483000315-a75dlsvj5v2881jq1m7me1mu7o6rgb29.apps.googleusercontent.com',
    iosBundleId: 'com.example.acrogate',
  );
}
